%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.20.0

-ifndef(pb_Bag).
-define(pb_Bag, true).

-define(pb_Bag_gpb_version, "4.20.0").


-ifndef('BAGREQ_PB_H').
-define('BAGREQ_PB_H', true).
-record('BagReq',
        {status                 :: integer() | undefined, % = 1, required, 32 bits
         num                    :: integer() | undefined % = 2, required, 32 bits
        }).
-endif.

-ifndef('BAGRESP_PB_H').
-define('BAGRESP_PB_H', true).
-record('BagResp',
        {num                    :: integer() | undefined % = 1, optional, 32 bits
        }).
-endif.

-endif.
