%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.20.0

-ifndef(pb_ClientCmdConstants).
-define(pb_ClientCmdConstants, true).

-define(pb_ClientCmdConstants_gpb_version, "4.20.0").



-endif.
