%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.20.0

-ifndef(pb_Mission).
-define(pb_Mission, true).

-define(pb_Mission_gpb_version, "4.20.0").


-ifndef('MISSIONREQ_PB_H').
-define('MISSIONREQ_PB_H', true).
-record('MissionReq',
        {mission                :: integer() | undefined, % = 1, optional, 32 bits
         score                  :: integer() | undefined % = 2, optional, 32 bits
        }).
-endif.

-ifndef('MISSIONRESP_PB_H').
-define('MISSIONRESP_PB_H', true).
-record('MissionResp',
        {mission                :: integer() | undefined, % = 1, optional, 32 bits
         score                  :: integer() | undefined, % = 2, optional, 32 bits
         max_score              :: integer() | undefined % = 3, optional, 32 bits
        }).
-endif.

-endif.
