%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.20.0

-ifndef(pb_messagebody).
-define(pb_messagebody, true).

-define(pb_messagebody_gpb_version, "4.20.0").


-ifndef('STATUS_PB_H').
-define('STATUS_PB_H', true).
-record('Status',
        {errorCode              :: 'OK' | 'FAIL' | integer() | undefined, % = 1, optional, enum Status.ErrorCode
         reason                 :: unicode:chardata() | undefined % = 2, optional
        }).
-endif.

-ifndef('MORNING_C2S_PB_H').
-define('MORNING_C2S_PB_H', true).
-record('Morning_c2s',
        {msgId                  :: non_neg_integer() | undefined, % = 1, optional, 64 bits
         command                :: 'AUTH' | 'PACKGE' | integer() | undefined, % = 2, optional, enum Command
         payload                :: iodata() | undefined % = 3, optional
        }).
-endif.

-ifndef('MORNING_S2C_PB_H').
-define('MORNING_S2C_PB_H', true).
-record('Morning_s2c',
        {msgId                  :: non_neg_integer() | undefined, % = 1, optional, 64 bits
         command                :: 'AUTH' | 'PACKGE' | integer() | undefined, % = 2, optional, enum Command
         status                 :: pb_messagebody:'Status'() | undefined, % = 3, optional
         payload                :: iodata() | undefined % = 4, optional
        }).
-endif.

-ifndef('LOGINREQ_PB_H').
-define('LOGINREQ_PB_H', true).
-record('LoginReq',
        {account                :: unicode:chardata() | undefined, % = 1, required
         loginPass              :: unicode:chardata() | undefined, % = 2, required
         loginType              :: integer() | undefined, % = 3, required, 32 bits
         version                :: unicode:chardata() | undefined, % = 4, optional
         jsVersion              :: unicode:chardata() | undefined, % = 5, optional
         channel                :: unicode:chardata() | undefined % = 6, optional
        }).
-endif.

-ifndef('LOGINRESP_PB_H').
-define('LOGINRESP_PB_H', true).
-record('LoginResp',
        {token                  :: unicode:chardata() | undefined, % = 1, required
         loginType              :: integer() | undefined % = 3, required, 32 bits
        }).
-endif.

-endif.
